name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        goarch: ["amd64"]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            .github/workflows/ci.yml
      - name: build
        run: GOOS=linux GOARCH=${{ matrix.goarch }} go build
        if: env.GIT_DIFF
      - name: test & coverage report creation
        run: |
          GOARCH=${{ matrix.goarch }} go test ./... -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic
        if: env.GIT_DIFF
      - uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          disable_search: true
          fail_ci_if_error: true
          files: ./coverage.txt
          use_oidc: true
        if: env.GIT_DIFF
